In [1]:
# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Imputación de nulos usando métodos avanzados estadísticos
# -----------------------------------------------------------------------
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

# Librerías de visualización
# -----------------------------------------------------------------------
import seaborn as sns
import matplotlib.pyplot as plt
# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [2]:
df_population = pd.read_csv("../data/data_countries/countries_population_year.csv")
df_population

,country,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Austria,8451860,8507786,8584926,8700471,8772865,8822267,8858775,8901064,8932664,8978929
1,Belgium,11137974,11180840,11237274,11311117,11351727,11398589,11455519,11522440,11554767,11617623
2,Bulgaria,7284552,7245677,7202198,7153784,7101859,7050034,7000039,6951482,6916548,6838937
3,Czechia,10516125,10512419,10538275,10553843,10578820,10610055,10649800,10693939,10701777,10516707
4,Denmark,5602628,5627235,5659715,5707251,5748769,5781190,5806081,5822763,5840045,5873420
5,Estonia,1320174,1315819,1314870,1315944,1315635,1319133,1324820,1328976,1330068,1331796
6,Finland,5426674,5451270,5471753,5487308,5503297,5513130,5517919,5525292,5533793,5548241
7,France,65600350,66165980,66458153,66638391,66809816,67026224,67177636,67320216,67656682,67871925
8,Germany,80523746,80767463,81197537,82175684,82521653,82792351,83019213,83166711,83155031,83237124
9,Iceland,321857,325671,329100,332529,338349,348450,356991,364134,368792,376248
10,Italy,59685227,60782668,60795612,60665551,60589445,60483973,59816673,59641488,59236213,59030133
11,Latvia,2023825,2001468,1986096,1968957,1950116,1934379,1919968,1907675,1893223,1875757
12,Liechtenstein,36838,37129,37366,37622,37810,38114,38378,38747,39055,39308
13,Lithuania,2971905,2943472,2921262,2888558,2847904,2808901,2794184,2794090,2795680,2805685
14,Luxembourg,537039,549680,562958,576249,590667,602005,613894,626108,634730,645397
15,Malta,422509,429424,439691,450415,460297,475701,493559,514564,516100,520971
16,Netherlands,16779575,16829289,16900726,16979120,17081507,17181084,17282163,17407585,17475415,17590672
17,Norway,5051275,5107970,5166493,5210721,5258317,5295619,5328212,5367580,5391369,5425270
18,Poland,38062535,38017856,38005614,37967209,37972964,37976687,37972812,37958138,37840001,37654247
19,Portugal,10487289,10427301,10374822,10341330,10309573,10291027,10276617,10295909,10298252,10352042
20,Serbia,7181505,7146759,7114393,7076372,7040272,7001444,6963764,6926705,6871547,6797105
21,Slovakia,5410836,5415949,5421349,5426252,5435343,5443120,5450421,5457873,5459781,5434712
22,Slovenia,2058821,2061085,2062874,2064188,2065895,2066880,2080908,2095861,2108977,2107180
23,Spain,46727890,46512199,46449565,46440099,46528024,46658447,46937060,47332614,47398695,47432893
24,Sweden,9555893,9644864,9747355,9851017,9995153,10120242,10230185,10327589,10379295,10452326
25,Switzerland,8039060,8139631,8237666,8327126,8419550,8484130,8544527,8606033,8670300,8738791

In [4]:
df_deaths = pd.read_csv("../data/data_countries/countries_deaths_year.csv")
df_deaths

,country,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Austria,79526,78252,83073,80669,83270,83975,83386,91599,91962
1,Belgium,109334,104755,110541,108097,109666,110693,108783,126896,112331
2,Bulgaria,104345,108952,110117,107580,109791,108526,108083,124735,148995
3,Czechia,109160,105665,111173,107750,111443,112920,112362,129289,139891
4,Denmark,52470,51340,52555,52824,53261,55232,53958,54645,57152
5,Estonia,15244,15484,15243,15392,15543,15751,15401,15811,18587
6,Finland,51472,52186,52492,53923,53722,54527,53949,55488,57659
7,France,569365,559435,593807,594005,606410,609747,613388,669064,661779
8,Germany,893825,868356,925200,910902,932272,954874,939520,985572,1023687
9,Iceland,2154,2049,2178,2309,2238,2254,2275,2304,2333
10,Italy,600744,598364,647571,615261,649061,633133,634417,740317,701346
11,Latvia,28691,28466,28478,28580,28757,28820,27719,28854,34600
12,Liechtenstein,246,268,252,271,249,274,263,319,271
13,Lithuania,41511,40252,41776,41106,40142,39574,38281,43547,47746
14,Luxembourg,3822,3841,3983,3967,4263,4318,4283,4609,4489
15,Malta,3236,3270,3442,3342,3571,3688,3688,4084,4163
16,Netherlands,141245,139223,147134,148997,150214,153363,151885,168678,170972
17,Norway,41131,40369,40676,40726,40774,40840,40684,40611,42002
18,Poland,387312,376467,394921,388009,402852,414200,409709,477355,519517
19,Portugal,106554,104843,108539,110573,109758,113051,111793,123358,124802
20,Serbia,100300,101247,103678,100834,103722,101655,101458,116850,136622
21,Slovakia,52089,51346,53826,52351,53914,54293,53234,59089,73461
22,Slovenia,19334,18886,19834,19689,20509,20485,20588,24016,23261
23,Spain,388600,393734,420408,408231,422037,425153,416102,492447,449149
24,Sweden,90402,88976,90907,90982,91972,92185,88766,98124,91958
25,Switzerland,64961,63938,67606,64964,66971,67088,67780,76195,71192

In [5]:
df_population.columns

Index(['country', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022'],
      dtype='object')

In [6]:
df_deaths.columns

Index(['country', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021'],
      dtype='object')

In [9]:
# List of columns to be renamed
columns_to_rename = ['2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022']

# Dictionary for renaming columns
rename_dict = {col: f"{col}_population" for col in columns_to_rename}

# Rename columns using the dictionary
df_population.rename(columns=rename_dict, inplace=True)

In [10]:
# List of columns to be renamed
columns_to_rename = ['2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021']

# Dictionary for renaming columns
rename_dict = {col: f"{col}_deaths" for col in columns_to_rename}

# Rename columns using the dictionary
df_deaths.rename(columns=rename_dict, inplace=True)

In [11]:
df_population

,country,2013_population,2014_population,2015_population,2016_population,2017_population,2018_population,2019_population,2020_population,2021_population,2022_population
0,Austria,8451860,8507786,8584926,8700471,8772865,8822267,8858775,8901064,8932664,8978929
1,Belgium,11137974,11180840,11237274,11311117,11351727,11398589,11455519,11522440,11554767,11617623
2,Bulgaria,7284552,7245677,7202198,7153784,7101859,7050034,7000039,6951482,6916548,6838937
3,Czechia,10516125,10512419,10538275,10553843,10578820,10610055,10649800,10693939,10701777,10516707
4,Denmark,5602628,5627235,5659715,5707251,5748769,5781190,5806081,5822763,5840045,5873420
5,Estonia,1320174,1315819,1314870,1315944,1315635,1319133,1324820,1328976,1330068,1331796
6,Finland,5426674,5451270,5471753,5487308,5503297,5513130,5517919,5525292,5533793,5548241
7,France,65600350,66165980,66458153,66638391,66809816,67026224,67177636,67320216,67656682,67871925
8,Germany,80523746,80767463,81197537,82175684,82521653,82792351,83019213,83166711,83155031,83237124
9,Iceland,321857,325671,329100,332529,338349,348450,356991,364134,368792,376248
10,Italy,59685227,60782668,60795612,60665551,60589445,60483973,59816673,59641488,59236213,59030133
11,Latvia,2023825,2001468,1986096,1968957,1950116,1934379,1919968,1907675,1893223,1875757
12,Liechtenstein,36838,37129,37366,37622,37810,38114,38378,38747,39055,39308
13,Lithuania,2971905,2943472,2921262,2888558,2847904,2808901,2794184,2794090,2795680,2805685
14,Luxembourg,537039,549680,562958,576249,590667,602005,613894,626108,634730,645397
15,Malta,422509,429424,439691,450415,460297,475701,493559,514564,516100,520971
16,Netherlands,16779575,16829289,16900726,16979120,17081507,17181084,17282163,17407585,17475415,17590672
17,Norway,5051275,5107970,5166493,5210721,5258317,5295619,5328212,5367580,5391369,5425270
18,Poland,38062535,38017856,38005614,37967209,37972964,37976687,37972812,37958138,37840001,37654247
19,Portugal,10487289,10427301,10374822,10341330,10309573,10291027,10276617,10295909,10298252,10352042
20,Serbia,7181505,7146759,7114393,7076372,7040272,7001444,6963764,6926705,6871547,6797105
21,Slovakia,5410836,5415949,5421349,5426252,5435343,5443120,5450421,5457873,5459781,5434712
22,Slovenia,2058821,2061085,2062874,2064188,2065895,2066880,2080908,2095861,2108977,2107180
23,Spain,46727890,46512199,46449565,46440099,46528024,46658447,46937060,47332614,47398695,47432893
24,Sweden,9555893,9644864,9747355,9851017,9995153,10120242,10230185,10327589,10379295,10452326
25,Switzerland,8039060,8139631,8237666,8327126,8419550,8484130,8544527,8606033,8670300,8738791

In [12]:
df_deaths

,country,2013_deaths,2014_deaths,2015_deaths,2016_deaths,2017_deaths,2018_deaths,2019_deaths,2020_deaths,2021_deaths
0,Austria,79526,78252,83073,80669,83270,83975,83386,91599,91962
1,Belgium,109334,104755,110541,108097,109666,110693,108783,126896,112331
2,Bulgaria,104345,108952,110117,107580,109791,108526,108083,124735,148995
3,Czechia,109160,105665,111173,107750,111443,112920,112362,129289,139891
4,Denmark,52470,51340,52555,52824,53261,55232,53958,54645,57152
5,Estonia,15244,15484,15243,15392,15543,15751,15401,15811,18587
6,Finland,51472,52186,52492,53923,53722,54527,53949,55488,57659
7,France,569365,559435,593807,594005,606410,609747,613388,669064,661779
8,Germany,893825,868356,925200,910902,932272,954874,939520,985572,1023687
9,Iceland,2154,2049,2178,2309,2238,2254,2275,2304,2333
10,Italy,600744,598364,647571,615261,649061,633133,634417,740317,701346
11,Latvia,28691,28466,28478,28580,28757,28820,27719,28854,34600
12,Liechtenstein,246,268,252,271,249,274,263,319,271
13,Lithuania,41511,40252,41776,41106,40142,39574,38281,43547,47746
14,Luxembourg,3822,3841,3983,3967,4263,4318,4283,4609,4489
15,Malta,3236,3270,3442,3342,3571,3688,3688,4084,4163
16,Netherlands,141245,139223,147134,148997,150214,153363,151885,168678,170972
17,Norway,41131,40369,40676,40726,40774,40840,40684,40611,42002
18,Poland,387312,376467,394921,388009,402852,414200,409709,477355,519517
19,Portugal,106554,104843,108539,110573,109758,113051,111793,123358,124802
20,Serbia,100300,101247,103678,100834,103722,101655,101458,116850,136622
21,Slovakia,52089,51346,53826,52351,53914,54293,53234,59089,73461
22,Slovenia,19334,18886,19834,19689,20509,20485,20588,24016,23261
23,Spain,388600,393734,420408,408231,422037,425153,416102,492447,449149
24,Sweden,90402,88976,90907,90982,91972,92185,88766,98124,91958
25,Switzerland,64961,63938,67606,64964,66971,67088,67780,76195,71192

In [13]:
df_death_population = df_deaths.merge(df_population, how='inner', on='country')

In [14]:
df_death_population

,country,2013_deaths,2014_deaths,2015_deaths,2016_deaths,2017_deaths,2018_deaths,2019_deaths,2020_deaths,2021_deaths,2013_population,2014_population,2015_population,2016_population,2017_population,2018_population,2019_population,2020_population,2021_population,2022_population
0,Austria,79526,78252,83073,80669,83270,83975,83386,91599,91962,8451860,8507786,8584926,8700471,8772865,8822267,8858775,8901064,8932664,8978929
1,Belgium,109334,104755,110541,108097,109666,110693,108783,126896,112331,11137974,11180840,11237274,11311117,11351727,11398589,11455519,11522440,11554767,11617623
2,Bulgaria,104345,108952,110117,107580,109791,108526,108083,124735,148995,7284552,7245677,7202198,7153784,7101859,7050034,7000039,6951482,6916548,6838937
3,Czechia,109160,105665,111173,107750,111443,112920,112362,129289,139891,10516125,10512419,10538275,10553843,10578820,10610055,10649800,10693939,10701777,10516707
4,Denmark,52470,51340,52555,52824,53261,55232,53958,54645,57152,5602628,5627235,5659715,5707251,5748769,5781190,5806081,5822763,5840045,5873420
5,Estonia,15244,15484,15243,15392,15543,15751,15401,15811,18587,1320174,1315819,1314870,1315944,1315635,1319133,1324820,1328976,1330068,1331796
6,Finland,51472,52186,52492,53923,53722,54527,53949,55488,57659,5426674,5451270,5471753,5487308,5503297,5513130,5517919,5525292,5533793,5548241
7,France,569365,559435,593807,594005,606410,609747,613388,669064,661779,65600350,66165980,66458153,66638391,66809816,67026224,67177636,67320216,67656682,67871925
8,Germany,893825,868356,925200,910902,932272,954874,939520,985572,1023687,80523746,80767463,81197537,82175684,82521653,82792351,83019213,83166711,83155031,83237124
9,Iceland,2154,2049,2178,2309,2238,2254,2275,2304,2333,321857,325671,329100,332529,338349,348450,356991,364134,368792,376248
10,Italy,600744,598364,647571,615261,649061,633133,634417,740317,701346,59685227,60782668,60795612,60665551,60589445,60483973,59816673,59641488,59236213,59030133
11,Latvia,28691,28466,28478,28580,28757,28820,27719,28854,34600,2023825,2001468,1986096,1968957,1950116,1934379,1919968,1907675,1893223,1875757
12,Liechtenstein,246,268,252,271,249,274,263,319,271,36838,37129,37366,37622,37810,38114,38378,38747,39055,39308
13,Lithuania,41511,40252,41776,41106,40142,39574,38281,43547,47746,2971905,2943472,2921262,2888558,2847904,2808901,2794184,2794090,2795680,2805685
14,Luxembourg,3822,3841,3983,3967,4263,4318,4283,4609,4489,537039,549680,562958,576249,590667,602005,613894,626108,634730,645397
15,Malta,3236,3270,3442,3342,3571,3688,3688,4084,4163,422509,429424,439691,450415,460297,475701,493559,514564,516100,520971
16,Netherlands,141245,139223,147134,148997,150214,153363,151885,168678,170972,16779575,16829289,16900726,16979120,17081507,17181084,17282163,17407585,17475415,17590672
17,Norway,41131,40369,40676,40726,40774,40840,40684,40611,42002,5051275,5107970,5166493,5210721,5258317,5295619,5328212,5367580,5391369,5425270
18,Poland,387312,376467,394921,388009,402852,414200,409709,477355,519517,38062535,38017856,38005614,37967209,37972964,37976687,37972812,37958138,37840001,37654247
19,Portugal,106554,104843,108539,110573,109758,113051,111793,123358,124802,10487289,10427301,10374822,10341330,10309573,10291027,10276617,10295909,10298252,10352042
20,Serbia,100300,101247,103678,100834,103722,101655,101458,116850,136622,7181505,7146759,7114393,7076372,7040272,7001444,6963764,6926705,6871547,6797105
21,Slovakia,52089,51346,53826,52351,53914,54293,53234,59089,73461,5410836,5415949,5421349,5426252,5435343,5443120,5450421,5457873,5459781,5434712
22,Slovenia,19334,18886,19834,19689,20509,20485,20588,24016,23261,2058821,2061085,2062874,2064188,2065895,2066880,2080908,2095861,2108977,2107180
23,Spain,388600,393734,420408,408231,422037,425153,416102,492447,449149,46727890,46512199,46449565,46440099,46528024,46658447,46937060,47332614,47398695,47432893
24,Sweden,90402,88976,90907,90982,91972,92185,88766,98124,91958,9555893,9644864,9747355,9851017,9995153,10120242,10230185,10327589,10379295,10452326
25,Switzerland,64961,63938,67606,64964,66971,67088,67780,76195,71192,8039060,8139631,8237666,8327126,8419550,8484130,8544527,8606033,8670300,8738791

In [16]:
df_death_population.drop('2022_population', axis=1, inplace=True)

In [17]:
columns_rename = ['2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021']

In [18]:
for col in columns_rename:
    df_death_population[f"{col}_tasa"] = df_death_population[f"{col}_deaths"]/df_death_population[f"{col}_population"]
df_death_population

,country,2013_deaths,2014_deaths,2015_deaths,2016_deaths,2017_deaths,2018_deaths,2019_deaths,2020_deaths,2021_deaths,2013_population,2014_population,2015_population,2016_population,2017_population,2018_population,2019_population,2020_population,2021_population,2013_tasa,2014_tasa,2015_tasa,2016_tasa,2017_tasa,2018_tasa,2019_tasa,2020_tasa,2021_tasa
0,Austria,79526,78252,83073,80669,83270,83975,83386,91599,91962,8451860,8507786,8584926,8700471,8772865,8822267,8858775,8901064,8932664,0.009409,0.009198,0.009677,0.009272,0.009492,0.009519,0.009413,0.010291,0.010295
1,Belgium,109334,104755,110541,108097,109666,110693,108783,126896,112331,11137974,11180840,11237274,11311117,11351727,11398589,11455519,11522440,11554767,0.009816,0.009369,0.009837,0.009557,0.009661,0.009711,0.009496,0.011013,0.009722
2,Bulgaria,104345,108952,110117,107580,109791,108526,108083,124735,148995,7284552,7245677,7202198,7153784,7101859,7050034,7000039,6951482,6916548,0.014324,0.015037,0.015289,0.015038,0.015459,0.015394,0.015440,0.017944,0.021542
3,Czechia,109160,105665,111173,107750,111443,112920,112362,129289,139891,10516125,10512419,10538275,10553843,10578820,10610055,10649800,10693939,10701777,0.010380,0.010051,0.010549,0.010210,0.010535,0.010643,0.010551,0.012090,0.013072
4,Denmark,52470,51340,52555,52824,53261,55232,53958,54645,57152,5602628,5627235,5659715,5707251,5748769,5781190,5806081,5822763,5840045,0.009365,0.009123,0.009286,0.009256,0.009265,0.009554,0.009293,0.009385,0.009786
5,Estonia,15244,15484,15243,15392,15543,15751,15401,15811,18587,1320174,1315819,1314870,1315944,1315635,1319133,1324820,1328976,1330068,0.011547,0.011768,0.011593,0.011697,0.011814,0.011940,0.011625,0.011897,0.013974
6,Finland,51472,52186,52492,53923,53722,54527,53949,55488,57659,5426674,5451270,5471753,5487308,5503297,5513130,5517919,5525292,5533793,0.009485,0.009573,0.009593,0.009827,0.009762,0.009890,0.009777,0.010043,0.010419
7,France,569365,559435,593807,594005,606410,609747,613388,669064,661779,65600350,66165980,66458153,66638391,66809816,67026224,67177636,67320216,67656682,0.008679,0.008455,0.008935,0.008914,0.009077,0.009097,0.009131,0.009939,0.009781
8,Germany,893825,868356,925200,910902,932272,954874,939520,985572,1023687,80523746,80767463,81197537,82175684,82521653,82792351,83019213,83166711,83155031,0.011100,0.010751,0.011394,0.011085,0.011297,0.011533,0.011317,0.011851,0.012311
9,Iceland,2154,2049,2178,2309,2238,2254,2275,2304,2333,321857,325671,329100,332529,338349,348450,356991,364134,368792,0.006692,0.006292,0.006618,0.006944,0.006614,0.006469,0.006373,0.006327,0.006326
10,Italy,600744,598364,647571,615261,649061,633133,634417,740317,701346,59685227,60782668,60795612,60665551,60589445,60483973,59816673,59641488,59236213,0.010065,0.009844,0.010652,0.010142,0.010712,0.010468,0.010606,0.012413,0.011840
11,Latvia,28691,28466,28478,28580,28757,28820,27719,28854,34600,2023825,2001468,1986096,1968957,1950116,1934379,1919968,1907675,1893223,0.014177,0.014223,0.014339,0.014515,0.014746,0.014899,0.014437,0.015125,0.018276
12,Liechtenstein,246,268,252,271,249,274,263,319,271,36838,37129,37366,37622,37810,38114,38378,38747,39055,0.006678,0.007218,0.006744,0.007203,0.006586,0.007189,0.006853,0.008233,0.006939
13,Lithuania,41511,40252,41776,41106,40142,39574,38281,43547,47746,2971905,2943472,2921262,2888558,2847904,2808901,2794184,2794090,2795680,0.013968,0.013675,0.014301,0.014231,0.014095,0.014089,0.013700,0.015585,0.017078
14,Luxembourg,3822,3841,3983,3967,4263,4318,4283,4609,4489,537039,549680,562958,576249,590667,602005,613894,626108,634730,0.007117,0.006988,0.007075,0.006884,0.007217,0.007173,0.006977,0.007361,0.007072
15,Malta,3236,3270,3442,3342,3571,3688,3688,4084,4163,422509,429424,439691,450415,460297,475701,493559,514564,516100,0.007659,0.007615,0.007828,0.007420,0.007758,0.007753,0.007472,0.007937,0.008066
16,Netherlands,141245,139223,147134,148997,150214,153363,151885,168678,170972,16779575,16829289,16900726,16979120,17081507,17181084,17282163,17407585,17475415,0.008418,0.008273,0.008706,0.008775,0.008794,0.008926,0.008789,0.009690,0.009784
17,Norway,41131,40369,40676,40726,40774,40840,40684,40611,42002,5051275,5107970,5166493,5210721,5258317,5295619,5328212,5367580,5391369,0.008143,0.007903,0.007873,0.007816,0.007754,0.007712,0.007636,0.007566,0.007791
18,Poland,387312,376467,394921,388009,402852,414200,409709,477355,519517,38062535,38017856,38005614,37967209,37972964,37976687,37972812,37958138,37840001,0.010176,0.009902,0.010391,0.010220,0.010609,0.010907,0.010790,0.012576,0.013729
19,Portugal,106554,104843,108539,110573,109758,113051,111793,123358,124802,10487289,10427301,10374822,10341330,10309573,10291027,10276617,10295909,10298252,0.010160,0.010055,0.010462,0.010692,0.010646,0.010985,0.010878,0.011981,0.012119
20,Serbia,100300,101247,103678,100834,103722,101655,101458,116850,136622,7181505,7146759,7114393,7076372,7040272,7001444,6963764,6926705,6871547,0.013966,0.014167,0.014573,0.014249,0.014733,0.014519,0.014569,0.016869,0.019882
21,Slovakia,52089,51346,53826,52351,53914,54293,53234,59089,73461,5410836,5415949,5421349,5426252,5435343,5443120,5450421,5457873,5459781,0.009627,0.009481,0.009929,0.009648,0.009919,0.009975,0.009767,0.010826,0.013455
22,Slovenia,19334,18886,19834,19689,20509,20485,20588,24016,23261,2058821,2061085,2062874,2064188,2065895,2066880,2080908,2095861,2108977,0.009391,0.009163,0.009615,0.009538,0.009927,0.009911,0.009894,0.011459,0.011030
23,Spain,388600,393734,420408,408231,422037,425153,416102,492447,449149,46727890,46512199,46449565,46440099,46528024,46658447,46937060,47332614,47398695,0.008316,0.008465,0.009051,0.008790,0.009071,0.009112,0.008865,0.010404,0.009476
24,Sweden,90402,88976,90907,90982,91972,92185,88766,98124,91958,9555893,9644864,9747355,9851017,9995153,10120242,10230185,10327589,10379295,0.009460,0.009225,0.009326,0.009236,0.009202,0.009109,0.008677,0.009501,0.008860
25,Switzerland,64961,63938,67606,64964,66971,67088,67780,76195,71192,8039060,8139631,8237666,8327126,8419550,8484130,8544527,8606033,8670300,0.008081,0.007855,0.008207,0.007801,0.007954,0.007907,0.007933,0.008854,0.008211

In [20]:
df_death_population.to_csv('../data/data_countries/countries_death_population_tasa.csv')